#!/usr/bin/env bash

script_dir="$(printf "%q " "$(realpath -s "$0")")"
cur_dir="${script_dir%/*}"

branch="master"
imgui_repo="https://raw.githubusercontent.com/ocornut/imgui/$branch"

srcs=("imgui.cpp"
      "imgui_demo.cpp"
      "imgui_draw.cpp"
      "imgui_tables.cpp"
      "imgui_widgets.cpp"
      "misc/cpp/imgui_stdlib.cpp"
      "backends/imgui_impl_glfw.cpp"
      "backends/imgui_impl_opengl3.cpp")

hdrs=("imgui.h"
      "imconfig.h"
      "imgui_internal.h"
      "imstb_rectpack.h"
      "imstb_textedit.h"
      "imstb_truetype.h"
      "misc/cpp/imgui_stdlib.h"
      "backends/imgui_impl_glfw.h"
      "backends/imgui_impl_opengl3.h"
      "backends/imgui_impl_opengl3_loader.h")

for file in "${srcs[@]}"; do
  curl --create-dirs -SsO --output-dir "$cur_dir/src" "$imgui_repo/$file" &
done

for file in "${hdrs[@]}"; do
  curl --create-dirs -SsO --output-dir "$cur_dir/include/imgui" "$imgui_repo/$file" &
done

curl -SsO --output-dir "$cur_dir" "$imgui_repo/LICENSE.txt" &

cmake="project(imgui)

add_library(imgui STATIC
"

for file in "${srcs[@]}"; do
  cmake+="  src/$(basename "$file")\n"
done

cmake+=")
add_library(imgui::imgui ALIAS imgui)

target_include_directories(imgui
  PRIVATE   include/imgui
  INTERFACE include
)"

echo -e "$cmake" > "$cur_dir/CMakeLists.txt" && wait
